import type { ParsedSchema } from '@yiyuan/core'

const TS_MAP: Record<string, string> = {
  string: 'string', text: 'string', number: 'number',
  boolean: 'boolean', timestamp: 'Date', auto: 'string', json: 'Record<string, any>',
}

function fieldToType(field: any): string {
  if (field.type === 'enum') return field.enumValues.map((v: string) => `'${v}'`).join(' | ')
  if (field.type === 'relation') return field.relation.type === 'hasOne' ? field.relation.model : `${field.relation.model}[]`
  return TS_MAP[field.type] ?? 'any'
}

export function generateTypes(schema: ParsedSchema): string {
  const L: string[] = [
    '// ─── 一元 自动生成 ─── 请勿手动修改',
    '// Generated by @yiyuan/compiler',
    '',
  ]

  for (const model of Object.values(schema.models)) {
    L.push(`export interface ${model.name} {`)
    for (const [key, field] of Object.entries(model.fields)) {
      L.push(`  ${key}${field.required ? '' : '?'}: ${fieldToType(field)}`)
    }
    L.push('}')
    L.push('')

    L.push(`export interface Create${model.name}Input {`)
    for (const [key, field] of Object.entries(model.fields)) {
      if (field.type === 'auto') continue
      if (field.type === 'relation' && field.relation?.type === 'hasMany') continue
      L.push(`  ${key}${field.required ? '' : '?'}: ${fieldToType(field)}`)
    }
    L.push('}')
    L.push('')

    L.push(`export interface Update${model.name}Input {`)
    L.push('  id: string')
    for (const [key, field] of Object.entries(model.fields)) {
      if (field.type === 'auto') continue
      if (field.type === 'relation' && field.relation?.type === 'hasMany') continue
      L.push(`  ${key}?: ${fieldToType(field)}`)
    }
    L.push('}')
    L.push('')
  }

  return L.join('\n')
}
