// ─── 一元 自动生成 ─── 请勿手动修改
// Generated by @yiyuan/compiler

export interface User {
  id?: string
  name: string
  email: string
  bio?: string
  tasks?: Task[]
}

export interface CreateUserInput {
  name: string
  email: string
  bio?: string
}

export interface UpdateUserInput {
  id: string
  name?: string
  email?: string
  bio?: string
}

export interface Task {
  id?: string
  title: string
  content?: string
  status?: 'todo' | 'doing' | 'done'
  priority?: 'low' | 'medium' | 'high'
  author?: User
  createdAt?: Date
}

export interface CreateTaskInput {
  title: string
  content?: string
  status?: 'todo' | 'doing' | 'done'
  priority?: 'low' | 'medium' | 'high'
  author?: User
  createdAt?: Date
}

export interface UpdateTaskInput {
  id: string
  title?: string
  content?: string
  status?: 'todo' | 'doing' | 'done'
  priority?: 'low' | 'medium' | 'high'
  author?: User
  createdAt?: Date
}
